<%- await include('@/view').catch(err => {
  console.error('Erro ao incluir o view:', err);
}) %>
